Add CRUD operations
Rafiduzzaman/blog-app pull request #2
Opened 2023-11-30 18:54 UTC by Rafiduzzaman

Pull Request Description:

**Description:**
This pull request focuses on creating models for the entities outlined in the ERD diagram, establishing associations between these models, and incorporating CRUD operations along with custom methods.

**Changes Made:**
1. **Model Creation:**
   - Created model classes for all entities based on the ERD diagram.
   - Established associations between models as per the specifications.
   - Set up the `author_id` column in the `posts` table as the foreign key for the `users` table.

2. **Data Insertion:**
   - Utilized the 'rails c' command to interact with the Rails console.
   - Created at least one user and four posts using the provided code snippets.

3. **CRUD Operations:**
   - Demonstrated the usage of CRUD methods to find, update, and delete entities.

4. **Custom Methods:**
   - Implemented additional methods in the models as specified:
     - **Users:**
       - Created a method returning the three most recent posts for a given user.
     - **Posts:**
       - Implemented a method updating the posts counter for a user.
       - Developed a method returning the five most recent comments for a given post.
     - **Comments:**
       - Added a method updating the comments counter for a post.
     - **Likes:**
       - Introduced a method updating the likes counter for a post.

5. **Verification:**
   - Use 'rails c' to verify the functionality of the implemented methods.

2023-11-30 20:44 UTC, prolajumokeoni requested changes
Hi @Rafiduzzaman 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Added User, Post, Comment and Like models inside app/models/ directory   ✅ 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 20:44 UTC, prolajumokeoni commented on app/models/post.rb
> +
- [ ] Please set the update post counter method  to `private` and please use the `after_save` method  to update counter after a post has been saved to the database 👍🏿 

```
 after_save :update_post_counter

  private
```

2023-11-30 20:44 UTC, prolajumokeoni commented on app/models/post.rb
> +  end
- [ ] Kindly remove the update_likes_counter method from `post.rb` as you have already it to your likes model 👍🏿

2023-11-30 20:44 UTC, prolajumokeoni commented on app/models/like.rb
> +
- [ ] It would be nice to add the after_save :update_likes_counter method to update the database after a like has been added 👍🏿

2023-11-30 20:44 UTC, prolajumokeoni commented on app/models/comment.rb
> +
It would be nice to add the after_save :update_comments_counter method to update the database after a comment has been added 👍🏿

2023-12-01 00:19 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @Rafiduzzaman, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 


## Highlights :green_circle: 

- Model methods to retrieve recent posts, comments, and to update posts and comments counter have been added

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 00:47 UTC, merged